spring:
  datasource:
    jdbcUrl: jdbc:h2:mem:planningpoker
    # For user and pass,  if the app there was in production env, we could use secrets management, Vault from hashcorp, or k8s secrets.
    # https://www.vaultproject.io/docs/what-is-vault
    # https://kubernetes.io/docs/concepts/configuration/secret/
    username: planningpoker
    password: planningpoker
  flyway:
    enabled: true
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: none
