CREATE TABLE PLANNING_SESSION(
    UUID uuid PRIMARY KEY,
    VERSION INT NOT NULL,
    TITLE VARCHAR(200) NOT NULL,
    DECK_TYPE VARCHAR(200) NOT NULL,
    CREATED_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
    LAST_MODIFIED_DATE TIMESTAMP WITH TIME ZONE NOT NULL
)