CREATE TABLE LINK_SESSION(
    UUID uuid PRIMARY KEY,
    VERSION INT NOT NULL,
    LINK VARCHAR(200) NOT NULL,
    PLANNING_SESSION_ID uuid NOT NULL,
    CREATED_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
    LAST_MODIFIED_DATE TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT FK_PLANNING_SESSION FOREIGN KEY (PLANNING_SESSION_ID) REFERENCES PLANNING_SESSION(UUID)
)