CREATE TABLE USER_STORY(
    UUID uuid PRIMARY KEY,
    VERSION INT NOT NULL,
    DESCRIPTION VARCHAR(200) NOT NULL,
    PLANNING_SESSION_ID uuid NOT NULL,
    CREATED_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
    LAST_MODIFIED_DATE TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT FK_PLANNING_SESSION_USER_STORY FOREIGN KEY (PLANNING_SESSION_ID) REFERENCES PLANNING_SESSION(UUID)
)