CREATE TABLE MEMBER_USER_STORY(
    UUID uuid PRIMARY KEY,
    VERSION INT NOT NULL,
    MEMBER_ID uuid NOT NULL,
    USER_STORY_ID uuid NOT NULL,
    PLANNING_SESSION_ID uuid NOT NULL,
    CREATED_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
    LAST_MODIFIED_DATE TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT FK_MEMBER_MEMBER_USER_STORY FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(UUID),
    CONSTRAINT FK_USER_STORY_MEMBER_USER_STORY FOREIGN KEY (USER_STORY_ID) REFERENCES USER_STORY(UUID),
    CONSTRAINT FK_PLANNING_SESSION_MEMBER_USER_STORY FOREIGN KEY (PLANNING_SESSION_ID) REFERENCES PLANNING_SESSION(UUID)
)